INSERT IGNORE INTO `llx_ea_coating` (`id`, `name`, `active`) VALUES
(1, 'LowE', 1),
(2, 'NONE', 1);

INSERT IGNORE INTO `llx_ea_interlayer` (`id`, `name`, `active`) VALUES
(1, 'CLEAR', 1),
(2, 'GREY (TURTLE)', 1),
(3, 'WHITE', 1);

INSERT IGNORE INTO `llx_ea_glasstype` (`id`, `name`, `active`) VALUES
(1, 'Insulated', 1),
(2, 'Laminated', 1);

INSERT IGNORE INTO `llx_ea_prodwintype` (`id`, `name`, `shortname`, `active`) VALUES
(1, 'Casement Window Series', 'CW', 1),
(2, 'Horizontal Rolling Series', 'HR', 1),
(3, 'Single Hung Series', 'SH', 1);

INSERT IGNORE INTO `llx_ea_productconfig` (`id`, `name`, `active`) VALUES
(1, 'EQUAL LITES', 1),
(2, 'O', 1),
(3, 'OX', 1),
(4, 'UNEQUAL LITES', 1),
(5, 'XL', 1),
(6, 'XO', 1),
(7, 'XOX 1/4 1/2 1/3', 1),
(8, 'XOX 1/3 1/3 1/3', 1),
(9, 'XR', 1);

INSERT IGNORE INTO `llx_c_actioncomm` (`id`, `code`, `type`, `libelle`, `module`, `active`, `todo`, `color`, `picto`, `position`) VALUES
(51, 'AC_ESTIMATE', 'user', 'Estimates', NULL, 1, NULL, '33b2ff', NULL, 6),
(52, 'AC_INSTALL', 'user', 'Installations', NULL, 1, NULL, '33ffe3', NULL, 7),
(53, 'AC_INSP', 'user', 'Inspections', NULL, 1, NULL, 'ff3333', NULL, 8),
(54, 'AC_SERVICE', 'user', 'Services Scheduled', NULL, 1, NULL, 'fdff33', NULL, 10),
(55, 'AC_PERMIT', 'user', 'Permits', NULL, 1, NULL, 'ffffoo', NULL, 9),
(56, 'AC_REMEASURE', 'user', 'Remeasurement', NULL, 1, NULL, '93d2ff', NULL, 11),
(57, 'AC_SERVICEPENDING', 'user', 'Services Pending', NULL, 1, NULL, 'edef23', NULL, 12);

INSERT IGNORE INTO `llx_ea_foliocities` (`id`, `county`, `folio_prefix`, `city`, `builddept`) VALUES
(1, 'Miami Dade', '01', 'MIAMI', 'CITY OF MIAMI'),
(2, 'Miami Dade', '02', 'MIAMI BEACH', 'CITY OF MIAMI BEACH'),
(3, 'Miami Dade', '03', 'CORAL GABLES', 'CITY OF CORAL GABLES'),
(4, 'Miami Dade', '04', 'HIALEAH', 'CITY OF HIALEAH'),
(5, 'Miami Dade', '05', 'MIAMI SPRINGS', 'CITY OF MIAMI SPRINGS'),
(6, 'Miami Dade', '06', 'NORTH MIAMI', 'CITY OF NORTH MIAMI'),
(7, 'Miami Dade', '07', 'NORTH MIAMI BEACH', 'CITY OF NORTH MIAMI BEACH'),
(8, 'Miami Dade', '08', 'OPA-LOCKA', 'CITY OF OPA-LOCKA'),
(9, 'Miami Dade', '09', 'SOUTH MIAMI', 'CITY OF SOUTH MIAMI'),
(10, 'Miami Dade', '10', 'HOMESTEAD', 'CITY OF HOMESTEAD'),
(11, 'Miami Dade', '11', 'MIAMI SHORES', 'VILLAGE OF MIAMI SHORES'),
(12, 'Miami Dade', '12', 'BAL HARBOUR', 'VILLAGE OF BAL HARBOUR'),
(13, 'Miami Dade', '13', 'BAY HARBOR', 'TOWN OF BAY HARBOR ISLANDS'),
(14, 'Miami Dade', '14', 'SURFSIDE', 'TOWN OF SURFSIDE'),
(15, 'Miami Dade', '15', 'WEST MIAMI', 'CITY OF WEST MIAMI'),
(16, 'Miami Dade', '16', 'FLORIDA CITY', 'CITY OF FLORIDA CITY'),
(17, 'Miami Dade', '17', 'BISCAYNE PARK', 'VILLAGE OF BISCAYNE PARK'),
(18, 'Miami Dade', '18', 'EL PORTAL', 'VILLAGE OF EL PORTAL'),
(19, 'Miami Dade', '19', 'GOLDEN BEACH ', 'TOWN OF GOLDEN BEACH'),
(20, 'Miami Dade', '20', 'PINECREST', 'VILLAGE OF PINECREST'),
(21, 'Miami Dade', '21', 'INDIAN CREEK VILLAGE', 'VILLAGE OF INDIAN CREEK'),
(22, 'Miami Dade', '22', 'MEDLEY', 'TOWN OF MEDLEY'),
(23, 'Miami Dade', '23', 'NORTH BAY VILLAGE', 'CITY OF NORTH BAY VILLAGE'),
(24, 'Miami Dade', '24', 'KEY BISCAYNE', 'VILLAGE OF KEY BISCAYNE'),
(25, 'Miami Dade', '25', 'SWEETWATER', 'CITY OF SWEETWATER'),
(26, 'Miami Dade', '26', 'VIRGINIA GARDENS', 'VILLAGE OF VIRGINIA GARDENS'),
(27, 'Miami Dade', '27', 'HIALEAH GARDENS', 'CITY OF HIALEAH GARDENS'),
(28, 'Miami Dade', '28', 'AVENTURA', 'CITY OF AVENTURA'),
(29, 'Miami Dade', '30', 'MIAMI', 'MIAMI DADE COUNTY'),
(30, 'Miami Dade', '31', 'SUNNY ISLES BEACH', 'CITY OF SUNNY ISLES BEACH'),
(31, 'Miami Dade', '32', 'MIAMI LAKES', 'TOWN OF MIAMI LAKES'),
(32, 'Miami Dade', '33', 'PALMETTO BAY ', 'VILLAGE OF PALMETTO BAY'),
(33, 'Miami Dade', '34', 'MIAMI GARDENS', 'CITY OF MIAMI GARDENS'),
(34, 'Miami Dade', '35', 'DORAL', 'CITY OF DORAL'),
(35, 'Miami Dade', '36', 'CUTLER BAY', 'TOWN OF CUTLER BAY'),
(36, 'Palm Beach', '00', 'UNINCORPORATED', 'PALM BEACH'),
(37, 'Palm Beach', '00', 'BOCA RATON', 'UNINCORPORATED BOCA RATON'),
(38, 'Palm Beach', '00', 'BOYNTON BEACH', 'UNINCORPORATED BOYNTON BEACH '),
(39, 'Palm Beach', '00', 'DELRAY BEACH', 'UNINCORPORATED DELRAY BEACH'),
(40, 'Palm Beach', '00', 'JUPITER', 'UNINCORPORATED JUPITER'),
(41, 'Palm Beach', '00', 'LAKE WORTH', 'UNINCORPORATED LAKE WORTH'),
(42, 'Palm Beach', '00', 'LOXAHATCHEE', 'UNINCORPORATED LOXAHATCHEE'),
(43, 'Palm Beach', '00', 'PALM BEACH GARDENS', 'UNINCORPORATED PALM BEACH GARDENS '),
(44, 'Palm Beach', '00', 'ROYAL PALM BEACH', 'UNINCORPORATED ROYAL PALM BEACH'),
(45, 'Palm Beach', '00', 'WELLINGTON', 'UNINCORPORATED WELLINGTON '),
(46, 'Palm Beach', '00', 'WEST PALM BEACH', 'UNINCORPORATED WEST PALM BEACH'),
(47, 'Palm Beach', '02', 'ATLANTIS', 'ATLANTIS'),
(48, 'Palm Beach', '04', 'BELLE GLADE', 'BELLE GLADE'),
(49, 'Palm Beach', '06', 'BOCA RATON', 'BOCA RATON'),
(50, 'Palm Beach', '08', 'BOYNTON BEACH', 'BOYNTON BEACH'),
(51, 'Palm Beach', '09', 'BRINY BREEZES', 'BRINY BREEZES'),
(52, 'Palm Beach', '10', 'WEST PALM BEACH', 'CLOUD LAKE'),
(53, 'Palm Beach', '12', 'DELRAY BEACH', 'DELRAY BEACH'),
(54, 'Palm Beach', '14', 'WEST PALM BEACH', 'GLEN RIDGE'),
(55, 'Palm Beach', '18', 'GREENACRES', 'GREENACRES'),
(56, 'Palm Beach', '20', 'GULF STREAM', 'GULF STREAM'),
(57, 'Palm Beach', '22', 'HAVERHILL', 'HAVERHILL'),
(58, 'Palm Beach', '24', 'HIGHLAND BEACH', 'HIGHLAND BEACH'),
(59, 'Palm Beach', '26', 'HYPOLUXO', 'HYPOLUXO'),
(60, 'Palm Beach', '28', 'JUNO BEACH', 'JUNO BEACH'),
(61, 'Palm Beach', '30', 'JUPITER', 'JUPITER'),
(62, 'Palm Beach', '32', 'JUPITER INLET COLONY', 'JUPITER INLET COLONY'),
(63, 'Palm Beach', '34', 'LAKE CLARKE SHORES', 'LAKE CLARKE SHORES'),
(64, 'Palm Beach', '36', 'LAKE PARK', 'LAKE PARK'),
(65, 'Palm Beach', '38', 'LAKE WORTH', 'LAKE WORTH'),
(66, 'Palm Beach', '40', 'LANTANA', 'LANTANA'),
(67, 'Palm Beach', '41', 'LOXAHATCHEE GROVES', 'LOXAHATCHEE GROVES'),
(68, 'Palm Beach', '42', 'MANALAPAN', 'MANALAPAN'),
(69, 'Palm Beach', '44', 'MANGONIA PARK', 'MANGONIA PARK'),
(70, 'Palm Beach', '46', 'OCEAN RIDGE', 'OCEAN RIDGE'),
(71, 'Palm Beach', '48', 'PAHOKEE', 'PAHOKEE'),
(72, 'Palm Beach', '50', 'PALM BEACH', 'PALM BEACH'),
(73, 'Palm Beach', '52', 'PALM BEACH GARDENS', 'PALM BEACH GARDENS'),
(74, 'Palm Beach', '54', 'PALM BEACH SHORES', 'PALM BEACH SHORES'),
(75, 'Palm Beach', '56', 'RIVIERA BEACH', 'RIVIERA BEACH'),
(76, 'Palm Beach', '58', 'SOUTH BAY', 'SOUTH BAY'),
(77, 'Palm Beach', '60', 'TEQUESTA', 'TEQUESTA'),
(78, 'Palm Beach', '62', 'SOUTH PALM BEACH', 'TOWN OF SOUTH PALM BEACH'),
(79, 'Palm Beach', '66', 'VILLAGE OF GOLF', 'VILLAGE OF GOLF'),
(80, 'Palm Beach', '68', 'NORTH PALM BEACH', 'VILLAGE OF NORTH PALM BEACH'),
(81, 'Palm Beach', '70', 'PALM SPRINGS', 'VILLAGE OF PALM SPRINGS'),
(82, 'Palm Beach', '72', 'ROYAL PALM BEACH', 'VILLAGE OF ROYAL PALM BEACH'),
(83, 'Palm Beach', '73', 'WELLINGTON', 'WELLINGTON'),
(84, 'Palm Beach', '74', 'WEST PALM BEACH', 'WEST PALM BEACH'),
(85, 'Broward', NULL, 'COCONUT CREEK', 'COCONUT CREEK'),
(86, 'Broward', NULL, 'COOPER CITY', 'COOPER CITY'),
(87, 'Broward', NULL, 'CORAL SPRINGS', 'CORAL SPRINGS'),
(88, 'Broward', NULL, 'DANIA BEACH', 'DANIA BEACH'),
(89, 'Broward', NULL, 'DAVIE', 'TOWN OF DAVIE'),
(90, 'Broward', NULL, 'DEERFIELD BEACH', 'DEERFIELD BEACH'),
(91, 'Broward', NULL, 'FORT LAUDERDALE', 'FORT LAUDERDALE'),
(92, 'Broward', NULL, 'HALLANDALE BEACH', 'HALLANDALE BEACH'),
(93, 'Broward', NULL, 'HOLLYWOOD', 'HOLLYWOOD'),
(94, 'Broward', NULL, 'LAUDERHILL', 'LAUDERHILL'),
(95, 'Broward', NULL, 'LIGHTHOUSE POINT', 'LIGHTHOUSE POINT'),
(96, 'Broward', NULL, 'NORTH LAUDERDALE', 'NORTH LAUDERDALE'),
(97, 'Broward', NULL, 'PARKLAND', 'PARKLAND'),
(98, 'Broward', NULL, 'PEMBROKE PINES', 'PEMBROKE PINES'),
(99, 'Broward', NULL, 'PLANTATION', 'PLANTATION'),
(100, 'Broward', NULL, 'POMPANO BEACH', 'POMPANO BEACH'),
(101, 'Broward', NULL, 'SUNRISE', 'CITY OF SUNRISE'),
(102, 'Broward', NULL, 'WESTON', 'CITY OF WESTON'),
(103, 'Broward', NULL, 'LAUDERDALE BY THE SEA', 'TOWN OF LAUDERDALE BY THE SEA'),
(104, 'Broward', NULL, 'LAUDERDALE LAKES', 'LAUDERDALE LAKES'),
(105, 'Broward', NULL, 'MARGATE', 'MARGATE'),
(106, 'Broward', NULL, 'MIRAMAR', 'MIRAMAR'),
(107, 'Broward', NULL, 'OAKLAND PARK', 'OAKLAND PARK'),
(108, 'Broward', NULL, 'PEMBROKE PARK', 'TOWN OF PEMBROKE PARK'),
(109, 'Broward', NULL, 'SOUTHWEST RANCHES', 'SOUTHWEST RANCHES'),
(110, 'Broward', NULL, 'TAMARAC', 'TAMARAC'),
(111, 'Broward', NULL, 'HILLSBORO BEACH', 'TOWN OF HILLSBORO BEACH'),
(112, 'Broward', NULL, 'SEA RANCH LAKES', 'SEA RANCH LAKES VILLAGE'),
(113, 'Broward', NULL, 'WEST PARK', 'CITY OF WEST PARK'),
(114, 'Broward', NULL, 'WILTON MANORS', 'WILTON MANORS'),
(115, NULL, NULL, NULL, 'FORT MYERS'),
(116, NULL, NULL, NULL, 'HOBE SOUND'),
(117, NULL, NULL, NULL, 'PALM CITY'),
(118, NULL, NULL, NULL, 'VILLAGE OF ISLAMORADA'),
(119, NULL, NULL, NULL, 'WESTLAKE'),
(120, NULL, NULL, NULL, 'KEY LARGO'),
(121, NULL, NULL, NULL, 'MONROE'),
(122, NULL, NULL, NULL, 'STUART');
