const itemData = {
  items: [
    {
      "PODescriptionID": 43113,
      "POID": 9383,
      "LineNumber": 1,
      "OPENINGW": 75,
      "OPENINGHT": 52,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 57,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 27.08333397,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43114,
      "POID": 9383,
      "LineNumber": 2,
      "OPENINGW": 75,
      "OPENINGHT": 52,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 57,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 27.08333397,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43115,
      "POID": 9383,
      "LineNumber": 3,
      "OPENINGW": 39,
      "OPENINGHT": 39,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 44,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 10.5625,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43116,
      "POID": 9383,
      "LineNumber": 4,
      "OPENINGW": 39,
      "OPENINGHT": 39,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 44,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 10.5625,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43117,
      "POID": 9383,
      "LineNumber": 5,
      "OPENINGW": 74,
      "OPENINGHT": 39,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 44,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 20.04166603,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43118,
      "POID": 9383,
      "LineNumber": 6,
      "OPENINGW": 27,
      "OPENINGHT": 27,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 32,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 5.0625,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43119,
      "POID": 9383,
      "LineNumber": 7,
      "OPENINGW": 54,
      "OPENINGHT": 39,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 44,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.625,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43120,
      "POID": 9383,
      "LineNumber": 8,
      "OPENINGW": 72,
      "OPENINGHT": 85,
      "TYPE": "STD",
      "LOCKIN": "IN",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 88,
      "ANGULARQTY": 2,
      "MOUNT": "WFL",
      "ALUMINST": 42.5,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43121,
      "POID": 9383,
      "LineNumber": 9,
      "OPENINGW": 54,
      "OPENINGHT": 39,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 44,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.625,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43122,
      "POID": 9383,
      "LineNumber": 10,
      "OPENINGW": 54,
      "OPENINGHT": 39,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 44,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.625,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43123,
      "POID": 9383,
      "LineNumber": 11,
      "OPENINGW": 39,
      "OPENINGHT": 40,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 45,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 10.83333302,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43124,
      "POID": 9383,
      "LineNumber": 12,
      "OPENINGW": 39,
      "OPENINGHT": 52,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 57,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.08333302,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43125,
      "POID": 9385,
      "LineNumber": 1,
      "OPENINGW": 96,
      "OPENINGHT": 82,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 93,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 54.66666794,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43126,
      "POID": 9385,
      "LineNumber": 2,
      "OPENINGW": 37,
      "OPENINGHT": 51,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 62,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13.10416698,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43127,
      "POID": 9385,
      "LineNumber": 3,
      "OPENINGW": 53,
      "OPENINGHT": 51,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 62,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 18.77083397,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43128,
      "POID": 9385,
      "LineNumber": 4,
      "OPENINGW": 53,
      "OPENINGHT": 51,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 62,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 18.77083397,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43129,
      "POID": 9385,
      "LineNumber": 5,
      "OPENINGW": 72,
      "OPENINGHT": 96,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 107,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 48,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43130,
      "POID": 9385,
      "LineNumber": 6,
      "OPENINGW": 53,
      "OPENINGHT": 51,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 62,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 18.77083397,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43131,
      "POID": 9385,
      "LineNumber": 7,
      "OPENINGW": 96,
      "OPENINGHT": 96,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 107,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 64,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43132,
      "POID": 9385,
      "LineNumber": 8,
      "OPENINGW": 37,
      "OPENINGHT": 51,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 62,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13.10416698,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43133,
      "POID": 9385,
      "LineNumber": 9,
      "OPENINGW": 53,
      "OPENINGHT": 73,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 84,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 26.86805534,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43134,
      "POID": 9390,
      "LineNumber": 1,
      "OPENINGW": 54,
      "OPENINGHT": 52,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 57,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 19.5,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43135,
      "POID": 9390,
      "LineNumber": 2,
      "OPENINGW": 107,
      "OPENINGHT": 75,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 80,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 55.72916794,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43136,
      "POID": 9390,
      "LineNumber": 3,
      "OPENINGW": 54,
      "OPENINGHT": 52,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 57,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 19.5,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43137,
      "POID": 9390,
      "LineNumber": 4,
      "OPENINGW": 41,
      "OPENINGHT": 83,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 88,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 23.63194466,
      "WINDOWSTYPE": "DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43138,
      "POID": 9394,
      "LineNumber": 1,
      "OPENINGW": 112,
      "OPENINGHT": 97,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "WO",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 102,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 75.44444275,
      "WINDOWSTYPE": "STORE FRONT",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43139,
      "POID": 9394,
      "LineNumber": 2,
      "OPENINGW": 112,
      "OPENINGHT": 97,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "WO",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 102,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 75.44444275,
      "WINDOWSTYPE": "STORE FRONT",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43140,
      "POID": 9394,
      "LineNumber": 3,
      "OPENINGW": 113,
      "OPENINGHT": 97,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "WO",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 102,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 76.11805725,
      "WINDOWSTYPE": "STORE FRONT",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43141,
      "POID": 9395,
      "LineNumber": 1,
      "OPENINGW": 96,
      "OPENINGHT": 77,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 82,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 51.33333206,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43142,
      "POID": 9395,
      "LineNumber": 2,
      "OPENINGW": 110,
      "OPENINGHT": 96,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 101,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 73.33333588,
      "WINDOWSTYPE": "TERRACE",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43143,
      "POID": 9395,
      "LineNumber": 3,
      "OPENINGW": 123,
      "OPENINGHT": 94,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 99,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 80.29166412,
      "WINDOWSTYPE": "TERRACE",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43144,
      "POID": 9395,
      "LineNumber": 4,
      "OPENINGW": 122,
      "OPENINGHT": 94,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 99,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 79.6388855,
      "WINDOWSTYPE": "TERRACE",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43145,
      "POID": 9395,
      "LineNumber": 5,
      "OPENINGW": 122,
      "OPENINGHT": 94,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 99,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 79.6388855,
      "WINDOWSTYPE": "TERRACE",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43146,
      "POID": 9395,
      "LineNumber": 6,
      "OPENINGW": 103,
      "OPENINGHT": 96,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 101,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 68.66666412,
      "WINDOWSTYPE": "TERRACE",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43147,
      "POID": 9399,
      "LineNumber": 1,
      "OPENINGW": 71,
      "OPENINGHT": 106,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 111,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 52.26388931,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43148,
      "POID": 9399,
      "LineNumber": 2,
      "OPENINGW": 77,
      "OPENINGHT": 106,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 111,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 56.68055725,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43149,
      "POID": 9399,
      "LineNumber": 3,
      "OPENINGW": 143,
      "OPENINGHT": 106,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 111,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 105.2638855,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43150,
      "POID": 9399,
      "LineNumber": 4,
      "OPENINGW": 69,
      "OPENINGHT": 106,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 111,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 50.79166794,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43151,
      "POID": 9399,
      "LineNumber": 5,
      "OPENINGW": 23,
      "OPENINGHT": 106,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 111,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 16.93055534,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43152,
      "POID": 9401,
      "LineNumber": 1,
      "OPENINGW": 106,
      "OPENINGHT": 51,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 56,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 37.54166794,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43153,
      "POID": 9401,
      "LineNumber": 2,
      "OPENINGW": 74,
      "OPENINGHT": 51,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 56,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 26.20833397,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43154,
      "POID": 9401,
      "LineNumber": 3,
      "OPENINGW": 54,
      "OPENINGHT": 48,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 53,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 18,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43155,
      "POID": 9401,
      "LineNumber": 4,
      "OPENINGW": 37,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 16.1875,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43156,
      "POID": 9403,
      "LineNumber": 1,
      "OPENINGW": 75,
      "OPENINGHT": 76,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 81,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 39.58333206,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43157,
      "POID": 9403,
      "LineNumber": 2,
      "OPENINGW": 37,
      "OPENINGHT": 76,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 81,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 19.52777863,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43158,
      "POID": 9403,
      "LineNumber": 3,
      "OPENINGW": 27,
      "OPENINGHT": 76,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 81,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.25,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43159,
      "POID": 9403,
      "LineNumber": 4,
      "OPENINGW": 48,
      "OPENINGHT": 44,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 49,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.66666698,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43160,
      "POID": 9403,
      "LineNumber": 5,
      "OPENINGW": 72,
      "OPENINGHT": 44,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 49,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 22,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43161,
      "POID": 9403,
      "LineNumber": 6,
      "OPENINGW": 74,
      "OPENINGHT": 82,
      "TYPE": "STD",
      "LOCKIN": "OUT IN",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WFL",
      "ALUMINST": 42.13888931,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43162,
      "POID": 9403,
      "LineNumber": 7,
      "OPENINGW": 72,
      "OPENINGHT": 39,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 44,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 19.5,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43163,
      "POID": 9403,
      "LineNumber": 8,
      "OPENINGW": 98,
      "OPENINGHT": 81,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 86,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 55.125,
      "WINDOWSTYPE": "SINGLE DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43164,
      "POID": 9403,
      "LineNumber": 9,
      "OPENINGW": 50,
      "OPENINGHT": 39,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 44,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13.54166698,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43165,
      "POID": 9405,
      "LineNumber": 1,
      "OPENINGW": 74,
      "OPENINGHT": 95,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 100,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 48.81944275,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43166,
      "POID": 9405,
      "LineNumber": 2,
      "OPENINGW": 66,
      "OPENINGHT": 124,
      "TYPE": "STD",
      "LOCKIN": "OUT IN",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 127,
      "ANGULARQTY": 2,
      "MOUNT": "WFL",
      "ALUMINST": 56.83333206,
      "WINDOWSTYPE": "FRONT DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43167,
      "POID": 9405,
      "LineNumber": 3,
      "OPENINGW": 74,
      "OPENINGHT": 95,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 100,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 48.81944275,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43168,
      "POID": 9405,
      "LineNumber": 4,
      "OPENINGW": 54,
      "OPENINGHT": 64,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 69,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 24,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43169,
      "POID": 9405,
      "LineNumber": 5,
      "OPENINGW": 54,
      "OPENINGHT": 64,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 69,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 24,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43170,
      "POID": 9405,
      "LineNumber": 6,
      "OPENINGW": 37,
      "OPENINGHT": 51,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 56,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13.10416698,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43171,
      "POID": 9405,
      "LineNumber": 7,
      "OPENINGW": 27,
      "OPENINGHT": 64,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 69,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 12,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43172,
      "POID": 9405,
      "LineNumber": 8,
      "OPENINGW": 47,
      "OPENINGHT": 86,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 89,
      "ANGULARQTY": 2,
      "MOUNT": "WFL",
      "ALUMINST": 28.06944466,
      "WINDOWSTYPE": "SINGLE DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43173,
      "POID": 9405,
      "LineNumber": 9,
      "OPENINGW": 145,
      "OPENINGHT": 99,
      "TYPE": "STD",
      "LOCKIN": "OUT IN",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 102,
      "ANGULARQTY": 2,
      "MOUNT": "WFL",
      "ALUMINST": 99.6875,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43174,
      "POID": 9405,
      "LineNumber": 10,
      "OPENINGW": 33,
      "OPENINGHT": 85,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 88,
      "ANGULARQTY": 2,
      "MOUNT": "WFL",
      "ALUMINST": 19.47916603,
      "WINDOWSTYPE": "SINGLE DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43175,
      "POID": 9405,
      "LineNumber": 11,
      "OPENINGW": 74,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 32.375,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43176,
      "POID": 9405,
      "LineNumber": 12,
      "OPENINGW": 74,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 32.375,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43177,
      "POID": 9405,
      "LineNumber": 13,
      "OPENINGW": 27,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 11.8125,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43178,
      "POID": 9405,
      "LineNumber": 14,
      "OPENINGW": 27,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 11.8125,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43179,
      "POID": 9405,
      "LineNumber": 15,
      "OPENINGW": 54,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 23.625,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43180,
      "POID": 9405,
      "LineNumber": 16,
      "OPENINGW": 74,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 32.375,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43181,
      "POID": 9406,
      "LineNumber": 1,
      "OPENINGW": 48,
      "OPENINGHT": 60,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 65,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 20,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43182,
      "POID": 9406,
      "LineNumber": 2,
      "OPENINGW": 36,
      "OPENINGHT": 60,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 65,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 15,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43183,
      "POID": 9406,
      "LineNumber": 3,
      "OPENINGW": 36,
      "OPENINGHT": 60,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 65,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 15,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43184,
      "POID": 9406,
      "LineNumber": 4,
      "OPENINGW": 72,
      "OPENINGHT": 99,
      "TYPE": "WO",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "WO",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 102,
      "ANGULARQTY": 2,
      "MOUNT": "WFL",
      "ALUMINST": 49.5,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43185,
      "POID": 9406,
      "LineNumber": 5,
      "OPENINGW": 24,
      "OPENINGHT": 60,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 65,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 10,
      "WINDOWSTYPE": "FIX GLASS",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43186,
      "POID": 9406,
      "LineNumber": 6,
      "OPENINGW": 48,
      "OPENINGHT": 60,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 65,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 20,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43187,
      "POID": 9406,
      "LineNumber": 7,
      "OPENINGW": 24,
      "OPENINGHT": 60,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 65,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 10,
      "WINDOWSTYPE": "FIX GLASS",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43188,
      "POID": 9406,
      "LineNumber": 8,
      "OPENINGW": 108,
      "OPENINGHT": 99,
      "TYPE": "WO",
      "LOCKIN": "OUT",
      "LOCKSIZE": "IN",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "WO",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 102,
      "ANGULARQTY": 2,
      "MOUNT": "WFL",
      "ALUMINST": 74.25,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43189,
      "POID": 9406,
      "LineNumber": 9,
      "OPENINGW": 36,
      "OPENINGHT": 60,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 65,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 15,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43190,
      "POID": 9408,
      "LineNumber": 1,
      "OPENINGW": 53,
      "OPENINGHT": 26,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 31,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 9.569444656,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43191,
      "POID": 9408,
      "LineNumber": 2,
      "OPENINGW": 53,
      "OPENINGHT": 26,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 31,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 9.569444656,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43192,
      "POID": 9408,
      "LineNumber": 3,
      "OPENINGW": 53,
      "OPENINGHT": 26,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 31,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 9.569444656,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43193,
      "POID": 9408,
      "LineNumber": 4,
      "OPENINGW": 71,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 39.44444275,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43194,
      "POID": 9408,
      "LineNumber": 5,
      "OPENINGW": 34,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.875,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43195,
      "POID": 9408,
      "LineNumber": 6,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43196,
      "POID": 9408,
      "LineNumber": 7,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43197,
      "POID": 9408,
      "LineNumber": 8,
      "OPENINGW": 53,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 23.1875,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43198,
      "POID": 9409,
      "LineNumber": 1,
      "OPENINGW": 52,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 22.75,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43199,
      "POID": 9409,
      "LineNumber": 2,
      "OPENINGW": 52,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 22.75,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43200,
      "POID": 9409,
      "LineNumber": 3,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43201,
      "POID": 9409,
      "LineNumber": 4,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43202,
      "POID": 9409,
      "LineNumber": 5,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43203,
      "POID": 9409,
      "LineNumber": 6,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43204,
      "POID": 9410,
      "LineNumber": 1,
      "OPENINGW": 53,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 23.1875,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43205,
      "POID": 9410,
      "LineNumber": 2,
      "OPENINGW": 106,
      "OPENINGHT": 63,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 68,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 46.375,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43206,
      "POID": 9410,
      "LineNumber": 3,
      "OPENINGW": 74,
      "OPENINGHT": 38,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 43,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 19.52777863,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43207,
      "POID": 9410,
      "LineNumber": 4,
      "OPENINGW": 26,
      "OPENINGHT": 38,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 43,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 6.861111164,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43208,
      "POID": 9410,
      "LineNumber": 5,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43209,
      "POID": 9410,
      "LineNumber": 6,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "SLIDING DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43210,
      "POID": 9412,
      "LineNumber": 1,
      "OPENINGW": 37,
      "OPENINGHT": 82,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 87,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 21.06944466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43211,
      "POID": 9412,
      "LineNumber": 2,
      "OPENINGW": 37,
      "OPENINGHT": 82,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 87,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 21.06944466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43212,
      "POID": 9412,
      "LineNumber": 3,
      "OPENINGW": 26,
      "OPENINGHT": 75,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 80,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13.54166698,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43213,
      "POID": 9412,
      "LineNumber": 4,
      "OPENINGW": 26,
      "OPENINGHT": 75,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 80,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13.54166698,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43214,
      "POID": 9412,
      "LineNumber": 5,
      "OPENINGW": 53,
      "OPENINGHT": 75,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 80,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 27.60416603,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43215,
      "POID": 9412,
      "LineNumber": 6,
      "OPENINGW": 72,
      "OPENINGHT": 26,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 31,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43216,
      "POID": 9412,
      "LineNumber": 7,
      "OPENINGW": 114,
      "OPENINGHT": 110,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 115,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 87.08333588,
      "WINDOWSTYPE": "FRENCH DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43217,
      "POID": 9412,
      "LineNumber": 8,
      "OPENINGW": 37,
      "OPENINGHT": 38,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 43,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 9.763889313,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43218,
      "POID": 9412,
      "LineNumber": 9,
      "OPENINGW": 19,
      "OPENINGHT": 76,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 81,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 10.02777767,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43219,
      "POID": 9412,
      "LineNumber": 10,
      "OPENINGW": 19,
      "OPENINGHT": 76,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 81,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 10.02777767,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43220,
      "POID": 9412,
      "LineNumber": 11,
      "OPENINGW": 72,
      "OPENINGHT": 76,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 81,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 38,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43221,
      "POID": 9412,
      "LineNumber": 12,
      "OPENINGW": 96,
      "OPENINGHT": 100,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 105,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 66.66666412,
      "WINDOWSTYPE": "FRENCH DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43222,
      "POID": 9412,
      "LineNumber": 13,
      "OPENINGW": 72,
      "OPENINGHT": 26,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 31,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43223,
      "POID": 9412,
      "LineNumber": 14,
      "OPENINGW": 72,
      "OPENINGHT": 26,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 31,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43224,
      "POID": 9412,
      "LineNumber": 15,
      "OPENINGW": 37,
      "OPENINGHT": 50,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 55,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 12.84722233,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43225,
      "POID": 9412,
      "LineNumber": 16,
      "OPENINGW": 53,
      "OPENINGHT": 50,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 55,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 18.40277863,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43226,
      "POID": 9412,
      "LineNumber": 17,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43227,
      "POID": 9412,
      "LineNumber": 18,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43228,
      "POID": 9412,
      "LineNumber": 19,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43229,
      "POID": 9412,
      "LineNumber": 20,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43230,
      "POID": 9412,
      "LineNumber": 21,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43231,
      "POID": 9412,
      "LineNumber": 22,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43232,
      "POID": 9412,
      "LineNumber": 23,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43233,
      "POID": 9412,
      "LineNumber": 24,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "FRENCH DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43234,
      "POID": 9412,
      "LineNumber": 25,
      "OPENINGW": 37,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 20.55555534,
      "WINDOWSTYPE": "GARAGE",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43235,
      "POID": 9413,
      "LineNumber": 1,
      "OPENINGW": 72,
      "OPENINGHT": 26,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 31,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43236,
      "POID": 9413,
      "LineNumber": 2,
      "OPENINGW": 72,
      "OPENINGHT": 26,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 31,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43237,
      "POID": 9413,
      "LineNumber": 3,
      "OPENINGW": 37,
      "OPENINGHT": 50,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 55,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 12.84722233,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43238,
      "POID": 9413,
      "LineNumber": 4,
      "OPENINGW": 53,
      "OPENINGHT": 50,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 55,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 18.40277863,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43239,
      "POID": 9413,
      "LineNumber": 5,
      "OPENINGW": 37,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 20.55555534,
      "WINDOWSTYPE": "GARAGE",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43240,
      "POID": 9413,
      "LineNumber": 6,
      "OPENINGW": 72,
      "OPENINGHT": 26,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 31,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 13,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43241,
      "POID": 9413,
      "LineNumber": 7,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43242,
      "POID": 9413,
      "LineNumber": 8,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43243,
      "POID": 9413,
      "LineNumber": 9,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43244,
      "POID": 9413,
      "LineNumber": 10,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43245,
      "POID": 9413,
      "LineNumber": 11,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43246,
      "POID": 9413,
      "LineNumber": 12,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43247,
      "POID": 9413,
      "LineNumber": 13,
      "OPENINGW": 37,
      "OPENINGHT": 55,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 60,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 14.13194466,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43248,
      "POID": 9413,
      "LineNumber": 14,
      "OPENINGW": 72,
      "OPENINGHT": 80,
      "TYPE": "STD",
      "LOCKIN": "OUT",
      "LOCKSIZE": "",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 85,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 40,
      "WINDOWSTYPE": "FRENCH DOOR",
      "EXTRAANGULARTYPE": "",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    },
    {
      "PODescriptionID": 43249,
      "POID": 9414,
      "LineNumber": 1,
      "OPENINGW": 25,
      "OPENINGHT": 18,
      "TYPE": "STD",
      "LOCKIN": "OUT IN",
      "LOCKSIZE": "-4",
      "UPPERTYPE": "STD",
      "LOWERTYPE": "STD",
      "ANGULARTYPE": "1x3",
      "ANGULARSIZE": 23,
      "ANGULARQTY": 2,
      "MOUNT": "WW",
      "ALUMINST": 3.125,
      "WINDOWSTYPE": "WINDOW",
      "EXTRAANGULARTYPE": "1x3",
      "EXTRAANGULARSIZE": 0,
      "EXTRAANGULARQTY": 0
    }
   ]
};

export default itemData;