DROP PROCEDURE IF EXISTS `copyPO`;
----
CREATE PROCEDURE `copyPO`(IN `copyPOID` INT, IN `initials` VARCHAR(10))
    MODIFIES SQL DATA
    COMMENT 'Creates a copy of an Estimate including it''s items'
BEGIN

	DECLARE newPOID int;
    
	INSERT INTO `llx_ea_po`(`PONUMBER`,  `PODATE`, `QUOTEDATE`, `Salesman`, `CUSTOMERNAME`, `CONTACTNAME`, `CUSTOMERADDRESS`, `ZIPCODE`, `CITY`, `STATE`, `PHONENUMBER1`, `PHONENUMBER2`, `FAXNUMBER`, `EMail`, `COLOR`, `HTVALUE`, `DESCRIPTIONOFWORK`, `OBSERVATION`, `TOTALTRACK`, `TAPCONS`, `TOTALLONG`, `FASTENERS`, `TOTALALUMINST`, `TOTALLINEARFT`, `OBSINST`, `SQINSTPRICE`, `INSTSALESPRICE`, `ESTHTVALUE`, `ESTOBSERVATION`, `INSTTIME`, `PERMIT`, `CUSTVALUE`, `CUSTOMIZE`, `SALES_TAX`, `SALESTAXAMOUNT`, `TOTALALUM`, `SALESPRICE`, `SQFEETPRICE`, `OTHERFEES`, `Check50`, `CheckAssIns`, `OrderCompleted`, `Check10YearsWarranty`, `Check10YearsFreeMaintenance`, `CheckFreeOpeningClosing`, `CheckNoPayment`, `YearsWarranty`, `LifeTimeWarranty`, `SignatureReq`, `Discount`, `customerId`, `invoiceId`, `permitId`)
		SELECT createPONUMBER(initials), `PODATE`, `QUOTEDATE`, `Salesman`, `CUSTOMERNAME`, `CONTACTNAME`, `CUSTOMERADDRESS`, `ZIPCODE`, `CITY`, `STATE`, `PHONENUMBER1`, `PHONENUMBER2`, `FAXNUMBER`, `EMail`, `COLOR`, `HTVALUE`, `DESCRIPTIONOFWORK`, `OBSERVATION`, `TOTALTRACK`, `TAPCONS`, `TOTALLONG`, `FASTENERS`, `TOTALALUMINST`, `TOTALLINEARFT`, `OBSINST`, `SQINSTPRICE`, `INSTSALESPRICE`, `ESTHTVALUE`, `ESTOBSERVATION`, `INSTTIME`, `PERMIT`, `CUSTVALUE`, `CUSTOMIZE`, `SALES_TAX`, `SALESTAXAMOUNT`, `TOTALALUM`, `SALESPRICE`, `SQFEETPRICE`, `OTHERFEES`, `Check50`, `CheckAssIns`, `OrderCompleted`, `Check10YearsWarranty`, `Check10YearsFreeMaintenance`, `CheckFreeOpeningClosing`, `CheckNoPayment`, `YearsWarranty`, `LifeTimeWarranty`, `SignatureReq`, `Discount`, `customerId`, null, null FROM `llx_ea_po` WHERE POID = copyPOID;

	SET newPOID = LAST_INSERT_ID();

	INSERT INTO `llx_ea_po_item`(`POID`, `LineNumber`, `OPENINGW`, `OPENINGHT`, `TRACK`, `TYPE`, `BLADESQTY`, `BLADESSTACK`, `BLADESLONG`, `LEFT`, `RIGHT`, `LOCKIN`, `LOCKSIZE`, `UPPERSIZE`, `UPPERTYPE`, `LOWERSIZE`, `LOWERTYPE`, `ANGULARTYPE`, `ANGULARSIZE`, `ANGULARQTY`, `MOUNT`, `ALUMINST`, `LINEARFT`, `OPENINGHT4`, `ALUMINST4`, `EST8HT`, `ALUM`, `WINDOWSTYPE`, `EXTRAANGULARTYPE`, `EXTRAANGULARSIZE`, `EXTRAANGULARQTY`, `SQFEETPRICE`, `ProductType`, `COLOR`, `MATERIAL`, `PROVIDER`, `INSTFEE`, `TUBETYPE`, `TUBESIZE`, `TUBEQTY`)
		SELECT newPOID, `LineNumber`, `OPENINGW`, `OPENINGHT`, `TRACK`, `TYPE`, `BLADESQTY`, `BLADESSTACK`, `BLADESLONG`, `LEFT`, `RIGHT`, `LOCKIN`, `LOCKSIZE`, `UPPERSIZE`, `UPPERTYPE`, `LOWERSIZE`, `LOWERTYPE`, `ANGULARTYPE`, `ANGULARSIZE`, `ANGULARQTY`, `MOUNT`, `ALUMINST`, `LINEARFT`, `OPENINGHT4`, `ALUMINST4`, `EST8HT`, `ALUM`, `WINDOWSTYPE`, `EXTRAANGULARTYPE`, `EXTRAANGULARSIZE`, `EXTRAANGULARQTY`, `SQFEETPRICE`, `ProductType`, `COLOR`, `MATERIAL`, `PROVIDER`, `INSTFEE`, `TUBETYPE`, `TUBESIZE`, `TUBEQTY` FROM `llx_ea_po_item` WHERE POID = copyPOID;

	SELECT newPOID;
    
END
